gitSourceBranch = "main"
classOrder = ["MatterPlasma"]

[docusaurus]
title = "Matter-Plasma"
tagline = ""

[home]
enabled = true

[footer]
copyright = "Copyright © 2023 Lucas Gangstad. Built with Moonwave and Docusaurus."
