[package]
name = "lasttalon/matter-plasma"
version = "0.1.0"
description = ""
license = "MIT"
authors = ["Lucas Gangstad <lucas@lasttalon.dev>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "*.spec.lua",
    "*.dev.lua",
    "tests",
    "docs",
    "aftman.toml",
    "moonwave.toml",
    "selene.toml",
    "stylua.toml",
    "testez-companion.toml",
    "sourcemap.json",
    "test.project.json",
    "testez.yaml",
]

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Matter = "evaera/matter@0.6.2"
Plasma = "evaera/plasma@0.4.2"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
